version: "3.7"

services:
  redis:
    image: redis:5.0-alpine
    command: redis-server --requirepass devpassword
    deploy:
      restart_policy:
        condition: none
    volumes:
      - redis:/data
    networks:
      - vos_net


  pgdb:
    image: astrolabe/vosdb:latest
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vos_net


  celery:
    image: astrolabe/cuts:latest
    command: celery worker -l debug -A cuts.blueprints.img.tasks
    deploy:
      restart_policy:
        condition: none
    networks:
      - vos_net
    depends_on:
      - redis


  dals:
    image: astrolabe/dals:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - _JAVA_OPTIONS=-Xms256m -Xmx2048m -Djava.security.egd=file:///dev/urandom
    volumes:
      - ./images:/vos/images
    networks:
      - vos_net
    depends_on:
      - pgdb


  cuts:
    image: astrolabe/cuts:latest
    deploy:
      restart_policy:
        condition: none
    environment:
      PYTHONUNBUFFERED: "true"
    volumes:
      - ./images:/vos/images:ro
    networks:
      - vos_net
    depends_on:
      - celery


  firefly:
    image: astrolabe/ffal:latest
    deploy:
      restart_policy:
        condition: none
    environment:
      # - DEBUG=TRUE
      - _JAVA_OPTIONS=-Xms512m -Xmx16384m -Djava.security.egd=file:///dev/urandom
    volumes:
      - ./images:/external:ro
    networks:
      - vos_net


  nginx:
    image: nginx:1.17.9
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /vos/config/nginx.conf:/etc/nginx/nginx.conf
      - /vos/config:/vos/config
    ports:
      - 80:80
      - 443:443
    networks:
      - vos_net
    depends_on:
      - cuts
      - dals
      - firefly


networks:
  vos_net:
    name: vos_net
    attachable: true

volumes:
  pgdata:
  redis:
