version: "3.9"

services:
  redis:
    image: redis:5.0.14-alpine
    command: redis-server --requirepass devpassword
    restart: "no"
    volumes:
      - redis:/usr/local/data/redis
    networks:
      - vos_net


  pgdb:
    image: astrolabe/vosdb:5.0
    restart: "no"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vos_net


  celery:
    image: astrolabe/cuts:5.0
    command: celery -A cuts.blueprints.img.tasks worker -l debug
    restart: "no"
    networks:
      - vos_net
    depends_on:
      - redis


  dals:
    image: astrolabe/dals:3.1
    restart: on-failure
    environment:
      # - _JAVA_OPTIONS=-Xms256m -Xmx2048m -Djava.security.egd=file:///dev/urandom
      - _JAVA_OPTIONS=-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom
    volumes:
      - /usr/local/data/vos/images:/usr/local/data/vos/images
    networks:
      - vos_net
    depends_on:
      - pgdb


  cuts:
    image: astrolabe/cuts:5.0
    restart: "no"
    environment:
      PYTHONUNBUFFERED: "true"
    volumes:
      - /usr/local/data/vos/images:/usr/local/data/vos/images:ro
    networks:
      - vos_net
    depends_on:
      - celery


  nginx:
    image: nginx:1.21.3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - /usr/local/data/vos/config/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/data/vos/config:/usr/local/data/vos/config
    ports:
      - 80:80
      - 443:443
    networks:
      - vos_net
    depends_on:
      - cuts
      - dals
      - firefly


networks:
  vos_net:
    name: vos_net
    attachable: true

volumes:
  pgdata:
  redis:
